const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
const NEW_PRODUCT = "NEW_PRODUCT";
const POST_PRODUCT = "POST_PRODUCT";

//Mensajes
const NEW_MESSAGE = "NEW_MESSAGE";
const UPDATE_MESSAGES = "UPDATE_MESSAGES";
const POST_MESSAGE = "POST_MESSAGE";

module.exports = {
  UPDATE_PRODUCTS,
  NEW_PRODUCT,
  POST_PRODUCT,
  NEW_MESSAGE,
  UPDATE_MESSAGES,
  POST_MESSAGE
}